### ISSUE TITLE
ORModel.MessageFilter seems to be plagued by function eating frogs

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/OpenReceptionFramework#12]
It no works!

At least I'm pretty sure that limitCount does nothing.

**Comment by rostgaard** [comment]
Damn frog and their munchies.

**Comment by rostgaard** [comment]
Do the other filter parameters work?

**Comment by ThomasLocke** [comment]
I haven't tried any of the other parameters - I just wanted to limit the amount returned, and that didn't do anything.
