### ISSUE TITLE
ORModel.MessageRecipientList seems to not contain bcc recipients

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/OpenReceptionFramework#13]
I don't know whether or not this is a bug in ORModel.MessageRecipientList or somewhere in the ServerStack. Reported here because I this is where I see the problem in the client.  :)

**Comment by rostgaard** [comment]
Are all the recipients different? Like in different contact@reception's ?

**Comment by ThomasLocke** [comment]
That seems to be the case with the Kim Rostgaard contact.

**Comment by rostgaard** [comment]
Oh. That guy. I know him. He's notoriously unreliable.
I'll build a test that checks that framework functions work as intended, and work my way up from there.
