### ISSUE TITLE
User id/name added to CalendarEntry

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/OpenReceptionFramework#4]
It would be nice if the user id/name of the creator/editor of a calendar entry could be associated with the entry.

Is this doable @rostgaard ?

I don't need/want anything fancy, just a quick reference to who did it. Right now we have the calendar entry id as a title attribute on each entry, but that doesn't say a whole lot, and requires some sort of log to figure out who wrote/edited the entry. A user id/name would be very nice.

**Comment by rostgaard** [comment]
Totally doable. I'm bumping this to 0.9 release though, but will most likely implement if sooner if there is nothing more critical.

**Comment by ThomasLocke** [comment]
A "last edit" timestamp wouldn't bee too bad either. Doable?  :)

**Comment by rostgaard** [comment]
Definitely! I would like, however, to stack all the database schema changes as they require fiddling around with quite a few deployments and projects.

**Comment by rostgaard** [comment]
User ID is part of the model now, and can be integrated into the UI. It has yet to be implemented in the server, and will for every object return a last-changed timestamp of 'null' (indicating 'never'), and a user ID of 0 (no user).

**Comment by rostgaard** [comment]
Using the latest server stack, you can get the calendar entry changes from;

 - https://github.com/Bitstackers/OpenReceptionFramework/blob/master/lib/service/service-reception.dart#L186
 - https://github.com/Bitstackers/OpenReceptionFramework/blob/master/lib/service/service-reception.dart#L174
 - https://github.com/Bitstackers/OpenReceptionFramework/blob/master/lib/service/service-contact.dart#L165
 - https://github.com/Bitstackers/OpenReceptionFramework/blob/master/lib/service/service-contact.dart#L177
