### ISSUE TITLE
Add List<String> messageBody to Model.Contact

### ISSUE THREAD

**Issue by ThomasLocke** [Bitstackers/OpenReceptionFramework#8]
A Contact may have some pre-defined "terms" for his/her messages, stuff that the receptionists MUST ask for.

In the current FrontDesk implementation these are simply presented as hard bracket enclosed words/sentences in the message body field.

I'm not sure about the messageBody name - I was pulling a blank when I wrote this issue, so feel free to come up with something better.

**Comment by rostgaard** [comment]
The test data still needs an update.

**Comment by ThomasLocke** [comment]
Contact.messagePrerequistes seems to return a List<List<String>> instead of a List<String>

I'm testing with this added to the attributes json in the database: "messagePrerequisites":["pre1","pre2"]

**Comment by ThomasLocke** [comment]
Works!
